const express = require("express");
const router = express.Router();
const Profileroute = require("./profile/profile");
const cmsroute = require("./cms");
const authroute = require("./auth");
const frontroutes = require("./front");
router.use("/profile", Profileroute);
router.use("/cms", cmsroute);
router.use("/auth", authroute);
router.use("/front", frontroutes);
module.exports = router;
